name = "JuliaAPL"
uuid = "d54601bc-8e46-489d-9eb7-2e348249bf46"
authors = ["Github Copilot", "Bruno Arias"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.9"

